const C = {
  procore: { _id: "conn-1", title: "Procore", slug: { current: "procore" }, shortDescription: "Sync with Procore projects" },
  plangrid: { _id: "conn-2", title: "PlanGrid", slug: { current: "plangrid" }, shortDescription: "Import plans from PlanGrid" },
  autodesk: { _id: "conn-3", title: "Autodesk Build", slug: { current: "autodesk-build" }, shortDescription: "Connect to Autodesk Build" },
  bluebeam: { _id: "conn-4", title: "Bluebeam", slug: { current: "bluebeam" }, shortDescription: "Import markups from Bluebeam" },
  sage: { _id: "conn-5", title: "Sage 300 CRE", slug: { current: "sage-300-cre" }, shortDescription: "Pull cost data from Sage" },
  msproject: { _id: "conn-6", title: "Microsoft Project", slug: { current: "microsoft-project" }, shortDescription: "Sync schedules from MS Project" },
  gdrive: { _id: "conn-7", title: "Google Drive", slug: { current: "google-drive" }, shortDescription: "Connect to Google Drive" },
  notion: { _id: "conn-8", title: "Notion", slug: { current: "notion" }, shortDescription: "Sync with Notion workspaces" },
};

export const PLACEHOLDER_AGENTS = [
  {
    _id: "agent-1",
    title: "Deep Search Agent",
    slug: { current: "deep-search" },
    shortDescription: "Search deeply across specs, drawings, RFIs, and submittals to get accurate answers grounded in project requirements.",
    description: "The Deep Search Agent scans across all connected project documents to surface precise, grounded answers to complex questions.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Search deeply across project documents for accurate, grounded answers.",
    inputs: ["Search query", "Connected project documents"],
    outputs: ["Grounded answers with source references", "Relevant document excerpts"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam, C.plangrid],
  },
  {
    _id: "agent-2",
    title: "Summary Spec Submittal Agent",
    slug: { current: "summary-spec-submittal" },
    shortDescription: "Compare submittals against specifications to quickly identify compliance gaps and reduce review risk.",
    description: "The Summary Spec Submittal Agent cross-references submittal packages against project specifications to flag compliance gaps.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Compare submittals against specs to identify compliance gaps.",
    inputs: ["Submittal package (PDF)", "Project specifications"],
    outputs: ["Compliance gap report", "Risk summary"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-3",
    title: "Document Comparison Agent",
    slug: { current: "document-comparison" },
    shortDescription: "Compare drawing sets to identify material changes, scope creep, and project risk before they hit the field.",
    description: "The Document Comparison Agent diffs drawing sets and documents to surface changes that could impact scope, cost, or schedule.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Identify material changes and scope creep by comparing drawing sets.",
    inputs: ["Drawing set A", "Drawing set B"],
    outputs: ["Change summary", "Risk assessment", "Marked-up comparison"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-4",
    title: "RFI Validator Agent",
    slug: { current: "rfi-validator" },
    shortDescription: "Validate RFIs before submission by identifying trivial requests and flagging cost, schedule, or quality implications.",
    description: "The RFI Validator Agent reviews draft RFIs to catch trivial requests and flag items with cost, schedule, or quality implications.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Validate RFIs before submission to reduce unnecessary back-and-forth.",
    inputs: ["Draft RFI", "Project documents"],
    outputs: ["Validation report", "Flagged implications"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-5",
    title: "Submittal-Builder Agent",
    slug: { current: "submittal-builder" },
    shortDescription: "Build complete, properly formatted submittal packages from cover page to final PDF in a guided workflow.",
    description: "The Submittal-Builder Agent guides users through creating complete submittal packages with proper formatting and documentation.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Build formatted submittal packages from cover page to final PDF.",
    inputs: ["Product data", "Spec sections", "Project info"],
    outputs: ["Complete submittal package (PDF)", "Cover sheet", "Compliance checklist"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-6",
    title: "Scope Checker Agent",
    slug: { current: "scope-checker" },
    shortDescription: "Eliminate scope gaps and overlaps by reconciling contracts, drawings, and project metadata before they become costly disputes.",
    description: "The Scope Checker Agent reconciles contracts, drawings, and metadata to surface scope gaps and overlaps early.",
    category: { title: "Cost Management", slug: { current: "cost-management" } },
    status: "live",
    jobToBeDone: "Reconcile contracts and drawings to eliminate scope gaps and overlaps.",
    inputs: ["Contracts", "Drawings", "Project metadata"],
    outputs: ["Scope gap report", "Overlap analysis", "Dispute risk assessment"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam, C.plangrid],
  },
  {
    _id: "agent-7",
    title: "SOP Agent",
    slug: { current: "sop-agent" },
    shortDescription: "Review SOPs to surface gaps, compliance risks, and clear improvement recommendations.",
    description: "The SOP Agent reviews standard operating procedures to identify gaps, compliance risks, and areas for improvement.",
    category: { title: "Safety & Compliance", slug: { current: "safety-compliance" } },
    status: "live",
    jobToBeDone: "Review SOPs for gaps and compliance risks.",
    inputs: ["SOP documents", "Regulatory standards"],
    outputs: ["Gap analysis", "Compliance risk report", "Improvement recommendations"],
    connectors: [C.procore, C.gdrive, C.notion, C.bluebeam],
  },
  {
    _id: "agent-8",
    title: "Site Safety Agent",
    slug: { current: "site-safety" },
    shortDescription: "Identify safety hazards from site photos, videos, and drawings with clear, field-ready findings.",
    description: "The Site Safety Agent analyzes site photos, videos, and drawings to identify safety hazards and produce field-ready findings.",
    category: { title: "Safety & Compliance", slug: { current: "safety-compliance" } },
    status: "live",
    jobToBeDone: "Identify safety hazards from visual site data.",
    inputs: ["Site photos", "Videos", "Safety drawings"],
    outputs: ["Hazard report", "Field-ready findings", "Priority ratings"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.plangrid],
  },
  {
    _id: "agent-9",
    title: "Deep Dive Spec Submittal Agent",
    slug: { current: "deep-dive-spec-submittal" },
    shortDescription: "Deeply review submittals against specs to surface risks, scope gaps, and next steps before approvals create downstream issues.",
    description: "The Deep Dive Spec Submittal Agent performs thorough submittal reviews against specifications to catch risks before approval.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Perform deep submittal reviews to prevent downstream issues.",
    inputs: ["Submittal package", "Full specification set"],
    outputs: ["Detailed review report", "Risk matrix", "Recommended next steps"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-10",
    title: "RFI Checker Agent",
    slug: { current: "rfi-checker" },
    shortDescription: "Check RFIs against existing project documents to resolve questions internally before sending them to the design team.",
    description: "The RFI Checker Agent cross-references RFIs against project documents to see if answers already exist internally.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Resolve RFI questions internally using existing project documents.",
    inputs: ["Draft RFI", "Project document set"],
    outputs: ["Resolution report", "Source references", "Remaining open items"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-11",
    title: "Mentor Agent",
    slug: { current: "mentor-agent" },
    shortDescription: "Get fast, clear guidance on systems, processes, and standards — with the option to dig deeper when needed.",
    description: "The Mentor Agent provides contextual guidance on systems, processes, and standards from your connected knowledge base.",
    category: { title: "Field Operations", slug: { current: "field-operations" } },
    status: "live",
    jobToBeDone: "Provide fast guidance on systems, processes, and standards.",
    inputs: ["Question or topic", "Connected knowledge bases"],
    outputs: ["Clear guidance", "Source references", "Deep-dive options"],
    connectors: [C.procore, C.gdrive, C.notion, C.bluebeam],
  },
  {
    _id: "agent-12",
    title: "Pre-Qualification Agent",
    slug: { current: "pre-qualification" },
    shortDescription: "Answer prequalification questions faster by reviewing uploaded checklists and supporting documents to complete responses accurately.",
    description: "The Pre-Qualification Agent reviews checklists and supporting documents to help complete prequalification responses accurately.",
    category: { title: "Preconstruction", slug: { current: "preconstruction" } },
    status: "live",
    jobToBeDone: "Complete prequalification responses accurately and quickly.",
    inputs: ["Prequalification checklist", "Supporting documents"],
    outputs: ["Completed responses", "Document references", "Gap list"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-13",
    title: "Fast AI Search Agent",
    slug: { current: "fast-ai-search" },
    shortDescription: "Get quick, structured answers by searching across connected spreadsheets, documents, databases, and web pages.",
    description: "The Fast AI Search Agent searches across all connected data sources to return quick, structured answers.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Search across all connected sources for quick structured answers.",
    inputs: ["Search query"],
    outputs: ["Structured answer", "Source list", "Related results"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam, C.notion],
  },
  {
    _id: "agent-14",
    title: "Daily Report Agent",
    slug: { current: "daily-report" },
    shortDescription: "Capture daily work activity quickly and generate a complete, structured daily report without missing details.",
    description: "The Daily Report Agent captures daily work activity and generates complete, structured reports automatically.",
    category: { title: "Field Operations", slug: { current: "field-operations" } },
    status: "live",
    jobToBeDone: "Generate complete daily reports from work activity data.",
    inputs: ["Daily activity notes", "Photos", "Labor data"],
    outputs: ["Structured daily report", "Photo log", "Progress summary"],
    connectors: [C.procore, C.gdrive, C.plangrid, C.bluebeam, C.autodesk],
  },
  {
    _id: "agent-15",
    title: "Change Order Agent",
    slug: { current: "change-order" },
    shortDescription: "Review change order requests to validate scope, cost, and schedule impacts using supporting project documentation.",
    description: "The Change Order Agent reviews change order requests against project documentation to validate scope, cost, and schedule impacts.",
    category: { title: "Cost Management", slug: { current: "cost-management" } },
    status: "live",
    jobToBeDone: "Validate change order scope, cost, and schedule impacts.",
    inputs: ["Change order request", "Project documentation", "Budget data"],
    outputs: ["Impact analysis", "Validation report", "Recommendation"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam, C.sage],
  },
  {
    _id: "agent-16",
    title: "Change Analyser Agent",
    slug: { current: "change-analyser" },
    shortDescription: "Analyze RFIs, NCRs, and field changes to understand patterns, root causes, and the cumulative impact of project changes.",
    description: "The Change Analyser Agent analyzes RFIs, NCRs, and field changes to reveal patterns and cumulative impact.",
    category: { title: "Cost Management", slug: { current: "cost-management" } },
    status: "live",
    jobToBeDone: "Analyze change patterns and their cumulative project impact.",
    inputs: ["RFIs", "NCRs", "Field change records"],
    outputs: ["Pattern analysis", "Root cause report", "Cumulative impact summary"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-17",
    title: "Audit Agent",
    slug: { current: "audit-agent" },
    shortDescription: "Automatically verifies project documents against audit requirements and flags compliance gaps before audits become emergencies.",
    description: "The Audit Agent verifies project documents against audit requirements and flags compliance gaps proactively.",
    category: { title: "Safety & Compliance", slug: { current: "safety-compliance" } },
    status: "live",
    jobToBeDone: "Verify project documents against audit requirements proactively.",
    inputs: ["Project documents", "Audit requirements"],
    outputs: ["Compliance report", "Gap list", "Priority actions"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-18",
    title: "Single Line Drawings Expert Agent",
    slug: { current: "single-line-drawings-expert" },
    shortDescription: "Extract and structure critical electrical system data from single-line drawings into clean, validated tables.",
    description: "The Single Line Drawings Expert Agent extracts electrical system data from single-line drawings and structures it into validated tables.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Extract structured electrical data from single-line drawings.",
    inputs: ["Single-line drawings (PDF/DWG)"],
    outputs: ["Structured data tables", "Validation report", "Equipment list"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
];

export const PLACEHOLDER_CONNECTORS = [
  {
    _id: "conn-1",
    title: "Procore",
    slug: { current: "procore" },
    shortDescription: "Sync project data, documents, and workflows with Procore's construction management platform.",
    description: "The Procore connector enables bidirectional sync between Datagrid agents and your Procore projects, including RFIs, submittals, and daily logs.",
    agentCount: 18,
  },
  {
    _id: "conn-9",
    title: "SharePoint",
    slug: { current: "sharepoint" },
    shortDescription: "Connect to SharePoint document libraries for enterprise document management.",
    description: "The SharePoint connector integrates with Microsoft SharePoint document libraries for enterprise-grade document management and collaboration.",
    agentCount: 18,
  },
  {
    _id: "conn-3",
    title: "Autodesk ACC",
    slug: { current: "autodesk-acc" },
    shortDescription: "Integrate with Autodesk Construction Cloud for BIM coordination and document control.",
    description: "The Autodesk ACC connector provides access to BIM models, documents, and project data in Autodesk Construction Cloud.",
    agentCount: 15,
  },
  {
    _id: "conn-10",
    title: "Oracle Aconex",
    slug: { current: "oracle-aconex" },
    shortDescription: "Connect to Oracle Aconex for global construction project collaboration.",
    description: "The Oracle Aconex connector enables access to project documents and workflows in Oracle's construction collaboration platform.",
    agentCount: 6,
  },
  {
    _id: "conn-11",
    title: "P6 Primavera",
    slug: { current: "p6-primavera" },
    shortDescription: "Sync with Oracle P6 Primavera for project scheduling and controls.",
    description: "The P6 Primavera connector syncs project schedules, tasks, and milestone data from Oracle's enterprise project management tool.",
    agentCount: 4,
  },
  {
    _id: "conn-12",
    title: "Trimble Connect",
    slug: { current: "trimble-connect" },
    shortDescription: "Sync with Trimble Connect for field-to-office data integration.",
    description: "The Trimble Connect connector bridges field and office data for seamless construction project coordination.",
    agentCount: 8,
  },
  {
    _id: "conn-13",
    title: "Quickbase",
    slug: { current: "quickbase" },
    shortDescription: "Connect to Quickbase for custom workflow and database integration.",
    description: "The Quickbase connector integrates with custom Quickbase workflows and databases for flexible project data access.",
    agentCount: 1,
  },
  {
    _id: "conn-8",
    title: "Notion",
    slug: { current: "notion" },
    shortDescription: "Access Notion workspaces for documentation and knowledge management.",
    description: "The Notion connector syncs with Notion workspaces, databases, and pages for knowledge management and documentation.",
    agentCount: 2,
  },
  {
    _id: "conn-14",
    title: "IMAP Email",
    slug: { current: "imap-email" },
    shortDescription: "Sync emails via IMAP for document and communication integration.",
    description: "The IMAP Email connector syncs emails for document extraction and communication tracking across your projects.",
    agentCount: 4,
  },
  {
    _id: "conn-15",
    title: "Slack",
    slug: { current: "slack" },
    shortDescription: "Connect to Slack for team communication integration.",
    description: "The Slack connector integrates with Slack channels for team communication, notifications, and agent interaction.",
    agentCount: 1,
  },
  {
    _id: "conn-16",
    title: "Egnyte",
    slug: { current: "egnyte" },
    shortDescription: "Access files stored in Egnyte for secure content collaboration.",
    description: "The Egnyte connector provides access to files stored in Egnyte for secure content collaboration and document management.",
    agentCount: 2,
  },
  {
    _id: "conn-17",
    title: "QuickBooks",
    slug: { current: "quickbooks" },
    shortDescription: "Connect to QuickBooks for financial and accounting integration.",
    description: "The QuickBooks connector integrates with QuickBooks for financial data, invoicing, and accounting workflows.",
    agentCount: 1,
  },
  {
    _id: "conn-7",
    title: "Google Drive",
    slug: { current: "google-drive" },
    shortDescription: "Access documents stored in Google Drive and Google Workspace.",
    description: "The Google Drive connector provides access to documents, spreadsheets, and files stored in Google Drive and Google Workspace.",
    agentCount: 14,
  },
];

export const PLACEHOLDER_CATEGORIES = [
  { _id: "cat-1", title: "Document Review", slug: { current: "document-review" }, description: "Agents that review and analyze construction documents." },
  { _id: "cat-2", title: "Field Operations", slug: { current: "field-operations" }, description: "Agents that streamline field reporting and operations." },
  { _id: "cat-3", title: "Cost Management", slug: { current: "cost-management" }, description: "Agents for budget tracking and cost analysis." },
  { _id: "cat-4", title: "Safety & Compliance", slug: { current: "safety-compliance" }, description: "Agents that help ensure jobsite safety and regulatory compliance." },
  { _id: "cat-5", title: "Preconstruction", slug: { current: "preconstruction" }, description: "Agents that assist with estimating, bid leveling, and pre-con workflows." },
];

export const PLACEHOLDER_GUIDES = [
  {
    _id: "guide-1",
    title: "How to Automate Construction Submittal Review with AI",
    slug: { current: "ai-agents-submittal-review" },
    excerpt: "Submittal review is one of the most time-consuming workflows in construction. Learn how AI agents can automate spec comparison, catch compliance gaps, and help reviewers focus on decisions rather than data comparison.",
    author: "Datagrid Team",
    publishedAt: "2024-12-15T00:00:00Z",
    readTime: 8,
    category: { title: "Workflows", slug: { current: "workflows" } },
    relatedAgentSlugs: ["summary-spec-submittal", "deep-dive-spec-submittal", "submittal-builder"],
    relatedConnectorSlugs: ["procore", "plangrid", "autodesk-build"],
  },
  {
    _id: "guide-2",
    title: "5 Ways AI is Transforming RFI Management in Construction",
    slug: { current: "ai-rfi-management" },
    excerpt: "RFIs are essential for construction communication, but poor quality RFIs and slow responses create project delays. Here's how AI is helping teams submit better RFIs and resolve questions faster.",
    author: "Datagrid Team",
    publishedAt: "2024-12-08T00:00:00Z",
    readTime: 6,
    category: { title: "Best Practices", slug: { current: "best-practices" } },
    relatedAgentSlugs: ["rfi-validator", "rfi-checker"],
    relatedConnectorSlugs: ["procore", "autodesk-build"],
  },
  {
    _id: "guide-3",
    title: "Construction Document Search: Beyond Keyword Matching",
    slug: { current: "construction-document-search" },
    excerpt: "Traditional keyword search doesn't work well for construction documents. Learn how AI-powered search understands context, relationships, and intent to deliver real answers instead of document lists.",
    author: "Datagrid Team",
    publishedAt: "2024-11-28T00:00:00Z",
    readTime: 7,
    category: { title: "Technology", slug: { current: "technology" } },
    relatedAgentSlugs: ["deep-search", "fast-ai-search"],
    relatedConnectorSlugs: ["procore", "google-drive"],
  },
  {
    _id: "guide-4",
    title: "Reducing Change Order Disputes with AI-Powered Analysis",
    slug: { current: "reducing-change-order-disputes" },
    excerpt: "Change orders are a leading source of disputes in construction. Discover how AI agents can validate scope, flag cost implications, and provide evidence-backed analysis before disagreements escalate.",
    author: "Datagrid Team",
    publishedAt: "2024-11-15T00:00:00Z",
    readTime: 9,
    category: { title: "Best Practices", slug: { current: "best-practices" } },
    relatedAgentSlugs: ["change-order", "change-analyser", "scope-checker"],
    relatedConnectorSlugs: ["procore", "sage-300-cre"],
  },
  {
    _id: "guide-5",
    title: "AI Safety Inspections: From Site Photos to Actionable Reports",
    slug: { current: "ai-safety-inspections" },
    excerpt: "Site safety inspections generate mountains of photos and notes that rarely get analyzed systematically. Learn how AI agents turn visual data into prioritized, field-ready safety findings.",
    author: "Datagrid Team",
    publishedAt: "2024-11-01T00:00:00Z",
    readTime: 5,
    category: { title: "Workflows", slug: { current: "workflows" } },
    relatedAgentSlugs: ["site-safety", "audit-agent"],
    relatedConnectorSlugs: ["procore", "plangrid"],
  },
  {
    _id: "guide-6",
    title: "The GC's Guide to AI Adoption in 2025",
    slug: { current: "gc-guide-ai-adoption" },
    excerpt: "Practical advice for general contractors looking to implement AI tools without disrupting existing workflows. Covers team buy-in, pilot programs, and measuring ROI on AI investments.",
    author: "Datagrid Team",
    publishedAt: "2024-10-20T00:00:00Z",
    readTime: 10,
    category: { title: "Industry", slug: { current: "industry" } },
    relatedAgentSlugs: ["deep-search", "submittal-builder", "daily-report"],
    relatedConnectorSlugs: ["procore", "google-drive"],
  },
];
