const C = {
  procore: { _id: "conn-1", title: "Procore", slug: { current: "procore" }, shortDescription: "Sync with Procore projects" },
  plangrid: { _id: "conn-2", title: "PlanGrid", slug: { current: "plangrid" }, shortDescription: "Import plans from PlanGrid" },
  autodesk: { _id: "conn-3", title: "Autodesk Build", slug: { current: "autodesk-build" }, shortDescription: "Connect to Autodesk Build" },
  bluebeam: { _id: "conn-4", title: "Bluebeam", slug: { current: "bluebeam" }, shortDescription: "Import markups from Bluebeam" },
  sage: { _id: "conn-5", title: "Sage 300 CRE", slug: { current: "sage-300-cre" }, shortDescription: "Pull cost data from Sage" },
  msproject: { _id: "conn-6", title: "Microsoft Project", slug: { current: "microsoft-project" }, shortDescription: "Sync schedules from MS Project" },
  gdrive: { _id: "conn-7", title: "Google Drive", slug: { current: "google-drive" }, shortDescription: "Connect to Google Drive" },
  notion: { _id: "conn-8", title: "Notion", slug: { current: "notion" }, shortDescription: "Sync with Notion workspaces" },
  oracleAconex: { _id: "conn-9", title: "Oracle Aconex", slug: { current: "oracle-aconex" }, shortDescription: "Connect to Oracle Aconex" },
  slack: { _id: "conn-10", title: "Slack", slug: { current: "slack" }, shortDescription: "Receive agent outputs in Slack" },
  egnyte: { _id: "conn-11", title: "Egnyte", slug: { current: "egnyte" }, shortDescription: "Sync documents from Egnyte" },
  sharepoint: { _id: "conn-12", title: "SharePoint", slug: { current: "sharepoint" }, shortDescription: "Connect to SharePoint" },
};

export const PLACEHOLDER_AGENTS = [
  {
    _id: "agent-1",
    title: "Deep Search Agent",
    slug: { current: "deep-search" },
    shortDescription: "Search deeply across specs, drawings, RFIs, and submittals to get accurate answers grounded in project requirements.",
    description: "The Deep Search Agent helps teams find precise, reliable answers by searching across connected project documents with a strong focus on drawings and specifications as the source of truth.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "It prioritizes spec sections and latest document revisions, cross-references submittals and RFIs against requirements, and highlights discrepancies when documents are out of alignment. This ensures answers are not just fast, but defensible and grounded in contract documents.",
    inputs: ["Search query", "Connected project documents"],
    outputs: ["Grounded answers with source references", "Relevant document excerpts"],
    connectors: [C.autodesk, C.oracleAconex, C.slack, C.egnyte, C.gdrive, C.sharepoint],
    commonUseCases: [
      "Confirming requirements directly from specifications",
      "Finding the latest approved information across drawings, RFIs, and submittals",
      "Identifying conflicts between specs, submittals, and RFIs",
      "Answering detailed technical or compliance questions",
      "Supporting design coordination and field decision-making",
    ],
    minimumKnowledge: [
      "Specifications and spec sections",
      "Drawings",
      "RFIs and submittals",
      "Project manuals and supporting documents",
    ],
    videoUrl: "",
  },
  {
    _id: "agent-2",
    title: "Summary Spec Submittal Agent",
    slug: { current: "summary-spec-submittal" },
    shortDescription: "Compare submittals against specifications to quickly identify compliance gaps and reduce review risk.",
    description: "The Summary Spec Submittal Agent cross-references submittal packages against project specifications to flag compliance gaps.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Compare submittals against specs to identify compliance gaps.",
    inputs: ["Submittal package (PDF)", "Project specifications"],
    outputs: ["Compliance gap report", "Risk summary"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-3",
    title: "Document Comparison Agent",
    slug: { current: "document-comparison" },
    shortDescription: "Compare drawing sets to identify material changes, scope creep, and project risk before they hit the field.",
    description: "The Document Comparison Agent diffs drawing sets and documents to surface changes that could impact scope, cost, or schedule.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Identify material changes and scope creep by comparing drawing sets.",
    inputs: ["Drawing set A", "Drawing set B"],
    outputs: ["Change summary", "Risk assessment", "Marked-up comparison"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-4",
    title: "RFI Validator Agent",
    slug: { current: "rfi-validator" },
    shortDescription: "Validate RFIs before submission by identifying trivial requests and flagging cost, schedule, or quality implications.",
    description: "The RFI Validator Agent reviews draft RFIs to catch trivial requests and flag items with cost, schedule, or quality implications.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Validate RFIs before submission to reduce unnecessary back-and-forth.",
    inputs: ["Draft RFI", "Project documents"],
    outputs: ["Validation report", "Flagged implications"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-5",
    title: "Submittal-Builder Agent",
    slug: { current: "submittal-builder" },
    shortDescription: "Build complete, properly formatted submittal packages from cover page to final PDF in a guided workflow.",
    description: "The Submittal-Builder Agent guides users through creating complete submittal packages with proper formatting and documentation.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Build formatted submittal packages from cover page to final PDF.",
    inputs: ["Product data", "Spec sections", "Project info"],
    outputs: ["Complete submittal package (PDF)", "Cover sheet", "Compliance checklist"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-6",
    title: "Scope Checker Agent",
    slug: { current: "scope-checker" },
    shortDescription: "Eliminate scope gaps and overlaps by reconciling contracts, drawings, and project metadata before they become costly disputes.",
    description: "The Scope Checker Agent reconciles contracts, drawings, and metadata to surface scope gaps and overlaps early.",
    category: { title: "Cost Management", slug: { current: "cost-management" } },
    status: "live",
    jobToBeDone: "Reconcile contracts and drawings to eliminate scope gaps and overlaps.",
    inputs: ["Contracts", "Drawings", "Project metadata"],
    outputs: ["Scope gap report", "Overlap analysis", "Dispute risk assessment"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam, C.plangrid],
  },
  {
    _id: "agent-7",
    title: "SOP Agent",
    slug: { current: "sop-agent" },
    shortDescription: "Review SOPs to surface gaps, compliance risks, and clear improvement recommendations.",
    description: "The SOP Agent reviews standard operating procedures to identify gaps, compliance risks, and areas for improvement.",
    category: { title: "Safety & Compliance", slug: { current: "safety-compliance" } },
    status: "live",
    jobToBeDone: "Review SOPs for gaps and compliance risks.",
    inputs: ["SOP documents", "Regulatory standards"],
    outputs: ["Gap analysis", "Compliance risk report", "Improvement recommendations"],
    connectors: [C.procore, C.gdrive, C.notion, C.bluebeam],
  },
  {
    _id: "agent-8",
    title: "Site Safety Agent",
    slug: { current: "site-safety" },
    shortDescription: "Identify safety hazards from site photos, videos, and drawings with clear, field-ready findings.",
    description: "The Site Safety Agent analyzes site photos, videos, and drawings to identify safety hazards and produce field-ready findings.",
    category: { title: "Safety & Compliance", slug: { current: "safety-compliance" } },
    status: "live",
    jobToBeDone: "Identify safety hazards from visual site data.",
    inputs: ["Site photos", "Videos", "Safety drawings"],
    outputs: ["Hazard report", "Field-ready findings", "Priority ratings"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.plangrid],
  },
  {
    _id: "agent-9",
    title: "Deep Dive Spec Submittal Agent",
    slug: { current: "deep-dive-spec-submittal" },
    shortDescription: "Deeply review submittals against specs to surface risks, scope gaps, and next steps before approvals create downstream issues.",
    description: "The Deep Dive Spec Submittal Agent performs thorough submittal reviews against specifications to catch risks before approval.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Perform deep submittal reviews to prevent downstream issues.",
    inputs: ["Submittal package", "Full specification set"],
    outputs: ["Detailed review report", "Risk matrix", "Recommended next steps"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-10",
    title: "RFI Checker Agent",
    slug: { current: "rfi-checker" },
    shortDescription: "Check RFIs against existing project documents to resolve questions internally before sending them to the design team.",
    description: "The RFI Checker Agent cross-references RFIs against project documents to see if answers already exist internally.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Resolve RFI questions internally using existing project documents.",
    inputs: ["Draft RFI", "Project document set"],
    outputs: ["Resolution report", "Source references", "Remaining open items"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-11",
    title: "Mentor Agent",
    slug: { current: "mentor-agent" },
    shortDescription: "Get fast, clear guidance on systems, processes, and standards — with the option to dig deeper when needed.",
    description: "The Mentor Agent provides contextual guidance on systems, processes, and standards from your connected knowledge base.",
    category: { title: "Field Operations", slug: { current: "field-operations" } },
    status: "live",
    jobToBeDone: "Provide fast guidance on systems, processes, and standards.",
    inputs: ["Question or topic", "Connected knowledge bases"],
    outputs: ["Clear guidance", "Source references", "Deep-dive options"],
    connectors: [C.procore, C.gdrive, C.notion, C.bluebeam],
  },
  {
    _id: "agent-12",
    title: "Pre-Qualification Agent",
    slug: { current: "pre-qualification" },
    shortDescription: "Answer prequalification questions faster by reviewing uploaded checklists and supporting documents to complete responses accurately.",
    description: "The Pre-Qualification Agent reviews checklists and supporting documents to help complete prequalification responses accurately.",
    category: { title: "Preconstruction", slug: { current: "preconstruction" } },
    status: "live",
    jobToBeDone: "Complete prequalification responses accurately and quickly.",
    inputs: ["Prequalification checklist", "Supporting documents"],
    outputs: ["Completed responses", "Document references", "Gap list"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-13",
    title: "Fast AI Search Agent",
    slug: { current: "fast-ai-search" },
    shortDescription: "Get quick, structured answers by searching across connected spreadsheets, documents, databases, and web pages.",
    description: "The Fast AI Search Agent searches across all connected data sources to return quick, structured answers.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Search across all connected sources for quick structured answers.",
    inputs: ["Search query"],
    outputs: ["Structured answer", "Source list", "Related results"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam, C.notion],
  },
  {
    _id: "agent-14",
    title: "Daily Report Agent",
    slug: { current: "daily-report" },
    shortDescription: "Capture daily work activity quickly and generate a complete, structured daily report without missing details.",
    description: "The Daily Report Agent captures daily work activity and generates complete, structured reports automatically.",
    category: { title: "Field Operations", slug: { current: "field-operations" } },
    status: "live",
    jobToBeDone: "Generate complete daily reports from work activity data.",
    inputs: ["Daily activity notes", "Photos", "Labor data"],
    outputs: ["Structured daily report", "Photo log", "Progress summary"],
    connectors: [C.procore, C.gdrive, C.plangrid, C.bluebeam, C.autodesk],
  },
  {
    _id: "agent-15",
    title: "Change Order Agent",
    slug: { current: "change-order" },
    shortDescription: "Review change order requests to validate scope, cost, and schedule impacts using supporting project documentation.",
    description: "The Change Order Agent reviews change order requests against project documentation to validate scope, cost, and schedule impacts.",
    category: { title: "Cost Management", slug: { current: "cost-management" } },
    status: "live",
    jobToBeDone: "Validate change order scope, cost, and schedule impacts.",
    inputs: ["Change order request", "Project documentation", "Budget data"],
    outputs: ["Impact analysis", "Validation report", "Recommendation"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam, C.sage],
  },
  {
    _id: "agent-16",
    title: "Change Analyser Agent",
    slug: { current: "change-analyser" },
    shortDescription: "Analyze RFIs, NCRs, and field changes to understand patterns, root causes, and the cumulative impact of project changes.",
    description: "The Change Analyser Agent analyzes RFIs, NCRs, and field changes to reveal patterns and cumulative impact.",
    category: { title: "Cost Management", slug: { current: "cost-management" } },
    status: "live",
    jobToBeDone: "Analyze change patterns and their cumulative project impact.",
    inputs: ["RFIs", "NCRs", "Field change records"],
    outputs: ["Pattern analysis", "Root cause report", "Cumulative impact summary"],
    connectors: [C.procore, C.gdrive, C.autodesk],
  },
  {
    _id: "agent-17",
    title: "Audit Agent",
    slug: { current: "audit-agent" },
    shortDescription: "Automatically verifies project documents against audit requirements and flags compliance gaps before audits become emergencies.",
    description: "The Audit Agent verifies project documents against audit requirements and flags compliance gaps proactively.",
    category: { title: "Safety & Compliance", slug: { current: "safety-compliance" } },
    status: "live",
    jobToBeDone: "Verify project documents against audit requirements proactively.",
    inputs: ["Project documents", "Audit requirements"],
    outputs: ["Compliance report", "Gap list", "Priority actions"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
  {
    _id: "agent-18",
    title: "Single Line Drawings Expert Agent",
    slug: { current: "single-line-drawings-expert" },
    shortDescription: "Extract and structure critical electrical system data from single-line drawings into clean, validated tables.",
    description: "The Single Line Drawings Expert Agent extracts electrical system data from single-line drawings and structures it into validated tables.",
    category: { title: "Document Review", slug: { current: "document-review" } },
    status: "live",
    jobToBeDone: "Extract structured electrical data from single-line drawings.",
    inputs: ["Single-line drawings (PDF/DWG)"],
    outputs: ["Structured data tables", "Validation report", "Equipment list"],
    connectors: [C.procore, C.gdrive, C.autodesk, C.bluebeam],
  },
];

export const PLACEHOLDER_CONNECTORS = [
  {
    _id: "conn-1",
    title: "AWS Timestream Integration",
    slug: { current: "aws-timestream-integration" },
    shortDescription: "Sync extracted document data directly to AWS Timestream. Automate time-series data ingestion for analytics, reporting, and IoT applications.",
    description: "Sync extracted document data directly to AWS Timestream. Automate time-series data ingestion for analytics, reporting, and IoT applications.",
    agentCount: 3,
  },
  {
    _id: "conn-2",
    title: "Accubid Anywhere",
    slug: { current: "accubid-anywhere" },
    shortDescription: "Optimize construction estimating with Accubid Anywhere integration.",
    description: "Optimize construction estimating with Accubid Anywhere integration.",
    agentCount: 8,
  },
  {
    _id: "conn-3",
    title: "Acumatica",
    slug: { current: "acumatica" },
    shortDescription: "Optimize business processes with Acumatica's cloud ERP solutions.",
    description: "Optimize business processes with Acumatica's cloud ERP solutions.",
    agentCount: 4,
  },
  {
    _id: "conn-4",
    title: "Airtable",
    slug: { current: "airtable" },
    shortDescription: "Organize and manage information effortlessly with collaborative database integration.",
    description: "Organize and manage information effortlessly with collaborative database integration.",
    agentCount: 3,
  },
  {
    _id: "conn-5",
    title: "Amazon AWS S3",
    slug: { current: "amazon-aws-s3" },
    shortDescription: "Optimize cloud storage and data retrieval with AWS S3 integration.",
    description: "Optimize cloud storage and data retrieval with AWS S3 integration.",
    agentCount: 5,
  },
  {
    _id: "conn-6",
    title: "Amazon Aurora",
    slug: { current: "amazon-aurora" },
    shortDescription: "Optimize data engineering and visualization with Amazon Aurora integration.",
    description: "Optimize data engineering and visualization with Amazon Aurora integration.",
    agentCount: 3,
  },
  {
    _id: "conn-7",
    title: "Amazon RDS",
    slug: { current: "amazon-rds" },
    shortDescription: "Scale and manage databases effortlessly with Amazon RDS integration.",
    description: "Scale and manage databases effortlessly with Amazon RDS integration.",
    agentCount: 3,
  },
  {
    _id: "conn-8",
    title: "Amazon Redshift",
    slug: { current: "amazon-redshift" },
    shortDescription: "Optimize data analysis with Amazon Redshift integration.",
    description: "Optimize data analysis with Amazon Redshift integration.",
    agentCount: 3,
  },
  {
    _id: "conn-9",
    title: "ArchiCAD",
    slug: { current: "archicad" },
    shortDescription: "Enhance project design and delivery with ArchiCAD integration.",
    description: "Enhance project design and delivery with ArchiCAD integration.",
    agentCount: 10,
  },
  {
    _id: "conn-10",
    title: "Asana",
    slug: { current: "asana" },
    shortDescription: "Streamline project management tasks with Asana integration.",
    description: "Streamline project management tasks with Asana integration.",
    agentCount: 3,
  },
  {
    _id: "conn-11",
    title: "Autodesk Construction Cloud (ACC)",
    slug: { current: "autodesk-acc" },
    shortDescription: "Enhance construction management with Autodesk Construction Cloud (ACC).",
    description: "Enhance construction management with Autodesk Construction Cloud (ACC).",
    agentCount: 15,
  },
  {
    _id: "conn-12",
    title: "Azure Blob Storage",
    slug: { current: "azure-blob-storage" },
    shortDescription: "Optimize cloud storage with Microsoft Azure Storage integration.",
    description: "Optimize cloud storage with Microsoft Azure Storage integration.",
    agentCount: 3,
  },
  {
    _id: "conn-13",
    title: "Azure Data Lake Storage",
    slug: { current: "azure-data-lake-storage" },
    shortDescription: "Optimize data analytics with Azure Data Lake Storage.",
    description: "Optimize data analytics with Azure Data Lake Storage.",
    agentCount: 3,
  },
  {
    _id: "conn-14",
    title: "Azure MySQL Database",
    slug: { current: "azure-mysql-database" },
    shortDescription: "Optimize data storage with Azure MySQL Database integration.",
    description: "Optimize data storage with Azure MySQL Database integration.",
    agentCount: 2,
  },
  {
    _id: "conn-15",
    title: "Azure PostgreSQL Database",
    slug: { current: "azure-postgresql-database" },
    shortDescription: "Optimize data storage with Azure PostgreSQL Database integration.",
    description: "Optimize data storage with Azure PostgreSQL Database integration.",
    agentCount: 2,
  },
  {
    _id: "conn-16",
    title: "Azure SQL Database",
    slug: { current: "azure-sql-database" },
    shortDescription: "Streamline data management with Azure SQL Database integration.",
    description: "Streamline data management with Azure SQL Database integration.",
    agentCount: 3,
  },
  {
    _id: "conn-17",
    title: "BIM 360 Build",
    slug: { current: "bim-360-build" },
    shortDescription: "Enhance document management with Autodesk BIM 360 integration.",
    description: "Enhance document management with Autodesk BIM 360 integration.",
    agentCount: 14,
  },
  {
    _id: "conn-18",
    title: "BIM Track",
    slug: { current: "bim-track" },
    shortDescription: "Improve issue tracking and project information management with Newforma.",
    description: "Improve issue tracking and project information management with Newforma.",
    agentCount: 10,
  },
  {
    _id: "conn-19",
    title: "BIM360 Docs",
    slug: { current: "bim360-docs" },
    shortDescription: "Integrate BIM 360 features for improved construction management.",
    description: "Integrate BIM 360 features for improved construction management.",
    agentCount: 14,
  },
  {
    _id: "conn-20",
    title: "BigCommerce",
    slug: { current: "bigcommerce" },
    shortDescription: "Streamline ecommerce operations with BigCommerce integration.",
    description: "Streamline ecommerce operations with BigCommerce integration.",
    agentCount: 2,
  },
  {
    _id: "conn-21",
    title: "BigQuery",
    slug: { current: "bigquery" },
    shortDescription: "Analyze large-scale datasets with ease using Google Cloud's fully managed data warehouse.",
    description: "Analyze large-scale datasets with ease using Google Cloud's fully managed data warehouse.",
    agentCount: 4,
  },
  {
    _id: "conn-22",
    title: "Bluebeam",
    slug: { current: "bluebeam" },
    shortDescription: "Import and manage markups from Bluebeam Revu.",
    description: "Import and manage markups from Bluebeam Revu.",
    agentCount: 14,
  },
  {
    _id: "conn-23",
    title: "Box",
    slug: { current: "box" },
    shortDescription: "Streamline content management and security with Box integration.",
    description: "Streamline content management and security with Box integration.",
    agentCount: 4,
  },
  {
    _id: "conn-24",
    title: "Bridgit",
    slug: { current: "bridgit" },
    shortDescription: "Enhance workforce management with Bridgit integration.",
    description: "Enhance workforce management with Bridgit integration.",
    agentCount: 6,
  },
  {
    _id: "conn-25",
    title: "BuildingConnected",
    slug: { current: "buildingconnected" },
    shortDescription: "Streamline preconstruction processes with BuildingConnected.",
    description: "Streamline preconstruction processes with BuildingConnected.",
    agentCount: 8,
  },
  {
    _id: "conn-26",
    title: "CMiC",
    slug: { current: "cmic" },
    shortDescription: "Optimize construction management processes with CMiC.",
    description: "Optimize construction management processes with CMiC.",
    agentCount: 12,
  },
  {
    _id: "conn-27",
    title: "Civil 3D",
    slug: { current: "civil-3d" },
    shortDescription: "Optimize land development, water, and transportation projects with 3D visualization.",
    description: "Optimize land development, water, and transportation projects with 3D visualization.",
    agentCount: 10,
  },
  {
    _id: "conn-28",
    title: "Databricks",
    slug: { current: "databricks" },
    shortDescription: "Empower data-driven insights with seamless integration.",
    description: "Empower data-driven insights with seamless integration.",
    agentCount: 3,
  },
  {
    _id: "conn-29",
    title: "DocuSign",
    slug: { current: "docusign" },
    shortDescription: "Automate data extraction from signed DocuSign documents. Sync contract details, signatures, and metadata to your workflows instantly.",
    description: "Automate data extraction from signed DocuSign documents. Sync contract details, signatures, and metadata to your workflows instantly.",
    agentCount: 5,
  },
{
    _id: "conn-30",
    title: "Dropbox",
    slug: { current: "dropbox" },
    shortDescription: "Enhance file storage and sharing with Dropbox integration.",
    description: "Enhance file storage and sharing with Dropbox integration.",
    agentCount: 4,
  },
  {
    _id: "conn-31",
    title: "Egnyte",
    slug: { current: "egnyte" },
    shortDescription: "Securely manage and govern content with Egnyte integration.",
    description: "Securely manage and govern content with Egnyte integration.",
    agentCount: 4,
  },
  {
    _id: "conn-32",
    title: "Emque",
    slug: { current: "emque" },
    shortDescription: "Enhance translation capabilities with Emque integration.",
    description: "Enhance translation capabilities with Emque integration.",
    agentCount: 1,
  },
  {
    _id: "conn-33",
    title: "Exchange",
    slug: { current: "exchange" },
    shortDescription: "Enhance shopping experience with Exchange's military discounts.",
    description: "Enhance shopping experience with Exchange's military discounts.",
    agentCount: 2,
  },
  {
    _id: "conn-34",
    title: "FRED",
    slug: { current: "fred" },
    shortDescription: "Optimize data transformation and visualization with FRED connector.",
    description: "Optimize data transformation and visualization with FRED connector.",
    agentCount: 2,
  },
{
    _id: "conn-35",
    title: "Fieldwire",
    slug: { current: "fieldwire" },
    shortDescription: "Optimize jobsite management with Fieldwire integration.",
    description: "Optimize jobsite management with Fieldwire integration.",
    agentCount: 12,
  },
  {
    _id: "conn-36",
    title: "Freshdesk",
    slug: { current: "freshdesk" },
    shortDescription: "Improve helpdesk operations with Freshdesk's robust features.",
    description: "Improve helpdesk operations with Freshdesk's robust features.",
    agentCount: 2,
  },
  {
    _id: "conn-37",
    title: "GitLab",
    slug: { current: "gitlab" },
    shortDescription: "Optimize DevOps workflows with GitLab integration.",
    description: "Optimize DevOps workflows with GitLab integration.",
    agentCount: 2,
  },
  {
    _id: "conn-38",
    title: "Github",
    slug: { current: "github" },
    shortDescription: "Enhance version control and collaboration with GitHub integration.",
    description: "Enhance version control and collaboration with GitHub integration.",
    agentCount: 2,
  },
{
    _id: "conn-39",
    title: "Google Analytics",
    slug: { current: "google-analytics" },
    shortDescription: "Track document processing metrics in Google Analytics.",
    description: "Track document processing metrics in Google Analytics.",
    agentCount: 2,
  },
  {
    _id: "conn-40",
    title: "Google Calendar",
    slug: { current: "google-calendar" },
    shortDescription: "Automatically create calendar events from extracted document data.",
    description: "Automatically create calendar events from extracted document data.",
    agentCount: 2,
  },
  {
    _id: "conn-41",
    title: "Google Cloud SQL - PostgreSQL",
    slug: { current: "google-cloud-sql-postgresql" },
    shortDescription: "Optimize database management with Google Cloud SQL PostgreSQL integration.",
    description: "Optimize database management with Google Cloud SQL PostgreSQL integration.",
    agentCount: 2,
  },
  {
    _id: "conn-42",
    title: "Google Cloud SQL - SQL Server",
    slug: { current: "google-cloud-sql-sql-server" },
    shortDescription: "Optimize data storage with Google Cloud SQL SQL Server integration.",
    description: "Optimize data storage with Google Cloud SQL SQL Server integration.",
    agentCount: 2,
  },
  {
    _id: "conn-43",
    title: "Google Cloud Storage",
    slug: { current: "google-cloud-storage" },
    shortDescription: "Enhance data storage solutions with Google Cloud Storage.",
    description: "Enhance data storage solutions with Google Cloud Storage.",
    agentCount: 3,
  },
  {
    _id: "conn-44",
    title: "Google Drive",
    slug: { current: "google-drive" },
    shortDescription: "Enhance cloud storage and collaboration with Google Drive integration.",
    description: "Enhance cloud storage and collaboration with Google Drive integration.",
    agentCount: 14,
  },
  {
    _id: "conn-45",
    title: "Google Sheets",
    slug: { current: "google-sheets" },
    shortDescription: "Export extracted document data directly to Google Sheets.",
    description: "Export extracted document data directly to Google Sheets.",
    agentCount: 4,
  },
  {
    _id: "conn-46",
    title: "HTTP Fetch",
    slug: { current: "http-fetch" },
    shortDescription: "Enhance web data retrieval with Fetch API integration.",
    description: "Enhance web data retrieval with Fetch API integration.",
    agentCount: 1,
  },
  {
    _id: "conn-47",
    title: "HelloSign",
    slug: { current: "hellosign" },
    shortDescription: "Enhance eSignature processes with HelloSign integration.",
    description: "Enhance eSignature processes with HelloSign integration.",
    agentCount: 3,
  },
  {
    _id: "conn-48",
    title: "Highwire",
    slug: { current: "highwire" },
    shortDescription: "Optimize construction operations with Highwire integration.",
    description: "Optimize construction operations with Highwire integration.",
    agentCount: 8,
  },
  {
    _id: "conn-49",
    title: "Hilti ON!Track",
    slug: { current: "hilti-ontrack" },
    shortDescription: "Track and manage construction assets effortlessly.",
    description: "Track and manage construction assets effortlessly.",
    agentCount: 6,
  },
  {
    _id: "conn-50",
    title: "HubSpot",
    slug: { current: "hubspot" },
    shortDescription: "Leverage HubSpot CRM for seamless marketing and sales automation.",
    description: "Leverage HubSpot CRM for seamless marketing and sales automation.",
    agentCount: 3,
  },
  {
    _id: "conn-51",
    title: "IMAP Email Sync",
    slug: { current: "imap-email" },
    shortDescription: "Process document attachments automatically from incoming emails.",
    description: "Process document attachments automatically from incoming emails.",
    agentCount: 4,
  },
  {
    _id: "conn-52",
    title: "Intercom",
    slug: { current: "intercom" },
    shortDescription: "Integrate Intercom to enhance AI-driven customer support workflows.",
    description: "Integrate Intercom to enhance AI-driven customer support workflows.",
    agentCount: 2,
  },
  {
    _id: "conn-53",
    title: "JDBC MySQL",
    slug: { current: "jdbc-mysql" },
    shortDescription: "Streamline data storage and management with JDBC MySQL integration.",
    description: "Streamline data storage and management with JDBC MySQL integration.",
    agentCount: 2,
  },
  {
    _id: "conn-54",
    title: "Jira",
    slug: { current: "jira" },
    shortDescription: "Streamline project management with Jira integration.",
    description: "Streamline project management with Jira integration.",
    agentCount: 3,
  },
  {
    _id: "conn-55",
    title: "LinkedIn Pages",
    slug: { current: "linkedin-pages" },
    shortDescription: "Sync extracted data with your LinkedIn Pages.",
    description: "Sync extracted data with your LinkedIn Pages.",
    agentCount: 1,
  },
  {
    _id: "conn-56",
    title: "MS Dynamics 365 NAV",
    slug: { current: "ms-dynamics-365-nav" },
    shortDescription: "Enhance business management with Dynamics 365 Business Central.",
    description: "Enhance business management with Dynamics 365 Business Central.",
    agentCount: 3,
  },
  {
    _id: "conn-57",
    title: "MS Fabric",
    slug: { current: "ms-fabric" },
    shortDescription: "Improve data management with MS Fabric.",
    description: "Improve data management with MS Fabric.",
    agentCount: 3,
  },
  {
    _id: "conn-58",
    title: "MS SQL Server",
    slug: { current: "ms-sql-server" },
    shortDescription: "Optimize data storage and querying with MS SQL Server integration.",
    description: "Optimize data storage and querying with MS SQL Server integration.",
    agentCount: 3,
  },
  {
    _id: "conn-59",
    title: "MariaDB",
    slug: { current: "mariadb" },
    shortDescription: "Integrate MariaDB for efficient data storage and management.",
    description: "Integrate MariaDB for efficient data storage and management.",
    agentCount: 2,
  },
  {
    _id: "conn-60",
    title: "Microsoft Excel",
    slug: { current: "microsoft-excel" },
    shortDescription: "Export extracted document data directly to Excel spreadsheets.",
    description: "Export extracted document data directly to Excel spreadsheets.",
    agentCount: 5,
  },
  {
    _id: "conn-61",
    title: "Microsoft Project",
    slug: { current: "microsoft-project" },
    shortDescription: "Sync schedules from Microsoft Project.",
    description: "Sync schedules from Microsoft Project.",
    agentCount: 8,
  },
  {
    _id: "conn-62",
    title: "Microsoft Teams",
    slug: { current: "microsoft-teams" },
    shortDescription: "Integrate Teams for unified communication and collaboration solutions.",
    description: "Integrate Teams for unified communication and collaboration solutions.",
    agentCount: 4,
  },
  {
    _id: "conn-63",
    title: "Mixpanel",
    slug: { current: "mixpanel" },
    shortDescription: "Optimize analytics with Mixpanel integration.",
    description: "Optimize analytics with Mixpanel integration.",
    agentCount: 2,
  },
  {
    _id: "conn-64",
    title: "Monday",
    slug: { current: "monday" },
    shortDescription: "Improve team collaboration and workflow management with Monday.com.",
    description: "Improve team collaboration and workflow management with Monday.com.",
    agentCount: 3,
  },
  {
    _id: "conn-65",
    title: "MongoDB",
    slug: { current: "mongodb" },
    shortDescription: "Streamline data storage and management with MongoDB integration.",
    description: "Streamline data storage and management with MongoDB integration.",
    agentCount: 3,
  },
  {
    _id: "conn-66",
    title: "Navisworks",
    slug: { current: "navisworks" },
    shortDescription: "Optimize 3D model reviews with Navisworks integration.",
    description: "Optimize 3D model reviews with Navisworks integration.",
    agentCount: 10,
  },
  {
    _id: "conn-67",
    title: "Notion",
    slug: { current: "notion" },
    shortDescription: "Optimize collaboration and project management with Notion integration.",
    description: "Optimize collaboration and project management with Notion integration.",
    agentCount: 4,
  },
  {
    _id: "conn-68",
    title: "OneDrive",
    slug: { current: "onedrive" },
    shortDescription: "Integrate OneDrive for scalable cloud storage solutions.",
    description: "Integrate OneDrive for scalable cloud storage solutions.",
    agentCount: 4,
  },
  {
    _id: "conn-69",
    title: "Oracle Aconex",
    slug: { current: "oracle-aconex" },
    shortDescription: "Improve project collaboration with Oracle Aconex integration.",
    description: "Improve project collaboration with Oracle Aconex integration.",
    agentCount: 10,
  },
  {
    _id: "conn-70",
    title: "Oracle Netsuite",
    slug: { current: "oracle-netsuite" },
    shortDescription: "Integrate NetSuite for comprehensive business management solutions.",
    description: "Integrate NetSuite for comprehensive business management solutions.",
    agentCount: 4,
  },
  {
    _id: "conn-71",
    title: "Oracle Primavera Cloud (OPC)",
    slug: { current: "oracle-primavera-cloud-opc" },
    shortDescription: "Optimize project management with Oracle Primavera Cloud integration.",
    description: "Optimize project management with Oracle Primavera Cloud integration.",
    agentCount: 8,
  },
  {
    _id: "conn-72",
    title: "Outreach",
    slug: { current: "outreach" },
    shortDescription: "Automate and optimize sales pipelines with Outreach integration.",
    description: "Automate and optimize sales pipelines with Outreach integration.",
    agentCount: 2,
  },
  {
    _id: "conn-73",
    title: "P6 EPPM",
    slug: { current: "p6-eppm" },
    shortDescription: "Enhance construction project management with Primavera P6 integration.",
    description: "Enhance construction project management with Primavera P6 integration.",
    agentCount: 8,
  },
  {
    _id: "conn-74",
    title: "P6 Primavera Data Service (PDS)",
    slug: { current: "p6-primavera" },
    shortDescription: "Optimize project portfolio management with seamless integration.",
    description: "Optimize project portfolio management with seamless integration.",
    agentCount: 8,
  },
{
    _id: "conn-75",
    title: "PlanGrid",
    slug: { current: "plangrid" },
    shortDescription: "Enhance project management with PlanGrid integration.",
    description: "Enhance project management with PlanGrid integration.",
    agentCount: 14,
  },
  {
    _id: "conn-76",
    title: "PostgreSQL",
    slug: { current: "postgresql" },
    shortDescription: "Optimize data storage and integration with powerful open-source database management.",
    description: "Optimize data storage and integration with powerful open-source database management.",
    agentCount: 3,
  },
  {
    _id: "conn-77",
    title: "Procore",
    slug: { current: "procore" },
    shortDescription: "Streamline construction management with Procore integration.",
    description: "Procore is a cloud-based construction management platform that streamlines collaboration among project stakeholders, including owners and contractors. Offering tools for document management, RFIs, submittals, scheduling, and quality control.\n\nEnhance decision-making, project management and efficiency by connecting your Procore account into Datagrid. With over 200 data connections, Datagrid can enhance your processes by leveraging AI, making you more efficient in managing and delivering projects on time.",
    prerequisites: [
      "Access to a Procore account with administrator permissions.",
      "Set up a Datagrid Service Account in Procore or set up Procore via Developer Managed Service Account in the Datagrid App.",
    ],
    setupSteps: [
      { title: "Configure", slug: "configure", bg: "bg-accent/5", icon: "M12 15a3 3 0 100-6 3 3 0 000 6zM19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z", subtitle: "Procore Configurations", items: [{ title: "Configure a Procore Service Account", slug: "procore-service-account" }, { title: "Configure a Procore DMSA Account in Datagrid", slug: "procore-dmsa-account" }, { title: "Configure Procore in Datagrid", slug: "procore-in-datagrid" }] },
      { title: "Set Up a Schedule", slug: "set-up-a-schedule", bg: "bg-accent/5", icon: "M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zM12 6v6l4 2", subtitle: "Schedule Configuration", items: [{ title: "Create a new schedule", slug: "create-schedule" }, { title: "Configure sync frequency", slug: "sync-frequency" }, { title: "Set up automated triggers", slug: "automated-triggers" }] },
      { title: "Create a Dataset", slug: "create-a-dataset", bg: "bg-accent/5", icon: "M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z", subtitle: "Dataset Setup", items: [{ title: "Select data sources", slug: "select-sources" }, { title: "Map fields and columns", slug: "map-fields" }, { title: "Configure output format", slug: "output-format" }] },
    ],
    dataEndpoints: [
      // Construction Financials
      { name: "Billing Periods", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget Changes", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget Views", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget View Detail Rows", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget View Snapshots", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget View Snapshots Detail Rows", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget View Summary Rows", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: false, read: true },
      { name: "Change Events", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Change Events v1.1", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Change Order Change Reasons", category: "Construction Financials", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Change Order Requests", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Contract Payments", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Direct Costs", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Line Item Types", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget Modifications", category: "Construction Financials", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Change Order Packages", category: "Construction Financials", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Potential Change Orders", category: "Construction Financials", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Purchase Order Contracts", category: "Construction Financials", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Work Order Contracts", category: "Construction Financials", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Manual Forecast Line Items", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Monitoring Resources", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Prime Contracts", category: "Construction Financials", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Requisitions (Subcontractor Invoices) for Project", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "RFQs", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Project WBS Segments", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Project Segment Items", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Budget Meta Data", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: false, read: true },
      { name: "Budget Line Item", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "WBS Codes", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Work Order Contract Detail Line Items", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Work Order Contract Line Items", category: "Construction Financials", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      // Core Tools
      { name: "Company Custom Field Sets", category: "Core Tools", level: "", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Documents", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Inactive Users", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Inactive Vendors", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Company Offices", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Programs", category: "Core Tools", level: "Company", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Trades", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Users", category: "Core Tools", level: "Company", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Vendors", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Cost Codes", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Custom fields", category: "Core Tools", level: "", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Documents", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Admin Equipment", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Line Item Types", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Locations", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Permission Manifest", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Permission Manifest", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Projects", category: "Core Tools", level: "Company", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Project Dates", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Project Inactive Users", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Project Memberships", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Project Permission Templates", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Project Roles", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Tools", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Users", category: "Core Tools", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Vendors", category: "Core Tools", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Vendor Insurances", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Sub Jobs", category: "Core Tools", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Submittal Statuses", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Submittal Types", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Tasks", category: "Core Tools", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Workflow Activity Histories", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Workflow Instances", category: "Core Tools", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      // Field Productivity
      { name: "Equipment Maintenance Log", category: "Field Productivity", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Managed Equipment", category: "Field Productivity", level: "", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Timecard Entries", category: "Field Productivity", level: "Projects", listShow: "Show", incrementalIngestion: true, read: true },
      // Project Management
      { name: "Accident Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Equipment Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Bids", category: "Project Management", level: "Company", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Bid Contacts", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "BIM Models", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "BIM Plans", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Calendar Items", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Call Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Coordination Issues", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Coordination Issue Activities", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Coordination Issue Activity Feed Items", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Construction Report Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Delivery Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Inspection Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Daily Log Count", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Manpower Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Delay Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Drawings", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Drawing Areas", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Dumpster Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Forms", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Images", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Image Categories", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Inspection Types", category: "Project Management", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Inspection Users", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Instructions", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Lookaheads", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Meetings", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Potential Assignees", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Potential RFI Managers", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "RFIs", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Schedule Resource Assignments", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Submittals", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Submittal Responses", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "RFI Replies", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Responses", category: "Project Management", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Safety Violation Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Schedule Metadata", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Schedule Resources", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Submittal Approvers", category: "Project Management", level: "", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Specification Sections", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Specification Section Divisions for a Project", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Specification Section Revisions", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Specification Sets", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Timecard Time Types", category: "Project Management", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Visitor Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Waste Logs", category: "Project Management", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      // Quality & Safety
      { name: "Action Plans", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklists", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist Items", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist (Inspection) Item Attachments", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist (Inspection) Comments", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist Default Distribution", category: "Quality & Safety", level: "", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist (Inspections) Item Attachments", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist Items Observations", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist List Inspection Type Filter Options", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: false, read: true },
      { name: "Checklist (Inspections) Sections", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist Signature Requests", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist Templates", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist Item Types", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Checklist Templates (Project)", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Company Checklist Sections", category: "Quality & Safety", level: "", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Company Checklist Templates", category: "Quality & Safety", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Company Checklist Template Sections", category: "Quality & Safety", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Deleted Punch Items", category: "Quality & Safety", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Environmentals", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Forms", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Incidents", category: "Quality & Safety", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Injuries", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Inspection Types", category: "Quality & Safety", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Inspection Users", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Near Misses", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Observations", category: "Quality & Safety", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Observation Assignee options", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Observation Types", category: "Quality & Safety", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Project Punch Item Templates", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Property Damages", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Punch Items", category: "Quality & Safety", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Punch List Manager options", category: "Quality & Safety", level: "Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Punch Item Types", category: "Quality & Safety", level: "Project", listShow: "List, Show", incrementalIngestion: true, read: true },
      { name: "Responses", category: "Quality & Safety", level: "Company", listShow: "List", incrementalIngestion: true, read: true },
      // Utilities
      { name: "Webhooks Hooks", category: "Utilities", level: "Company, Project", listShow: "List", incrementalIngestion: true, read: true },
      { name: "Triggers", category: "Utilities", level: "", listShow: "List", incrementalIngestion: true, read: true },
    ],
    agentCount: 18,
  },
  {
    _id: "conn-78",
    title: "QuickBooks",
    slug: { current: "quickbooks" },
    shortDescription: "Automate invoice and receipt processing into QuickBooks.",
    description: "Automate invoice and receipt processing into QuickBooks.",
    agentCount: 4,
  },
  {
    _id: "conn-79",
    title: "Quickbase",
    slug: { current: "quickbase" },
    shortDescription: "Optimize communication and collaboration with Quickbase integration.",
    description: "Optimize communication and collaboration with Quickbase integration.",
    agentCount: 4,
  },
  {
    _id: "conn-80",
    title: "Remarcable",
    slug: { current: "remarcable" },
    shortDescription: "Optimize construction asset management with Remarcable integration.",
    description: "Optimize construction asset management with Remarcable integration.",
    agentCount: 6,
  },
  {
    _id: "conn-81",
    title: "Revit",
    slug: { current: "revit" },
    shortDescription: "Enhance 3D design and automation with Revit integration.",
    description: "Enhance 3D design and automation with Revit integration.",
    agentCount: 12,
  },
  {
    _id: "conn-82",
    title: "Revizto",
    slug: { current: "revizto" },
    shortDescription: "Improve BIM collaboration with Revizto integration.",
    description: "Improve BIM collaboration with Revizto integration.",
    agentCount: 10,
  },
  {
    _id: "conn-83",
    title: "Riskcast",
    slug: { current: "riskcast" },
    shortDescription: "Optimize construction processes with Riskcast integration.",
    description: "Optimize construction processes with Riskcast integration.",
    agentCount: 6,
  },
  {
    _id: "conn-84",
    title: "SAP BW/4HANA",
    slug: { current: "sap-bw-4hana" },
    shortDescription: "Simplify data storage and integration with SAP BW/4HANA connector.",
    description: "Simplify data storage and integration with SAP BW/4HANA connector.",
    agentCount: 3,
  },
  {
    _id: "conn-85",
    title: "SAP S/4HANA",
    slug: { current: "sap-s-4hana" },
    shortDescription: "Optimize enterprise resource planning with SAP S/4HANA integration.",
    description: "Optimize enterprise resource planning with SAP S/4HANA integration.",
    agentCount: 4,
  },
  {
    _id: "conn-86",
    title: "SYNCHRO 4D Pro",
    slug: { current: "synchro-4d-pro" },
    shortDescription: "Optimize 3D modeling and scheduling with SYNCHRO 4D integration.",
    description: "Optimize 3D modeling and scheduling with SYNCHRO 4D integration.",
    agentCount: 8,
  },
  {
    _id: "conn-87",
    title: "Sage 300 CRE",
    slug: { current: "sage-300-cre" },
    shortDescription: "Pull cost data from Sage 300 CRE.",
    description: "Pull cost data from Sage 300 CRE.",
    agentCount: 8,
  },
  {
    _id: "conn-88",
    title: "Sage 300 Cloud",
    slug: { current: "sage-300-cloud" },
    shortDescription: "Manage finances and operations efficiently with Sage 300 Cloud.",
    description: "Manage finances and operations efficiently with Sage 300 Cloud.",
    agentCount: 6,
  },
  {
    _id: "conn-89",
    title: "Sage Intacct",
    slug: { current: "sage-intacct" },
    shortDescription: "Streamline financial management with Sage Intacct integration.",
    description: "Streamline financial management with Sage Intacct integration.",
    agentCount: 5,
  },
  {
    _id: "conn-90",
    title: "Salesforce",
    slug: { current: "salesforce" },
    shortDescription: "Enhance customer relationship management with Salesforce and AI.",
    description: "Enhance customer relationship management with Salesforce and AI.",
    agentCount: 4,
  },
  {
    _id: "conn-91",
    title: "Sentry",
    slug: { current: "sentry" },
    shortDescription: "Optimize error resolution with real-time monitoring using Sentry integration.",
    description: "Optimize error resolution with real-time monitoring using Sentry integration.",
    agentCount: 1,
  },
  {
    _id: "conn-92",
    title: "Sharepoint",
    slug: { current: "sharepoint" },
    shortDescription: "Collaborate and manage documents efficiently with SharePoint integration.",
    description: "Collaborate and manage documents efficiently with SharePoint integration.",
    agentCount: 16,
  },
  {
    _id: "conn-93",
    title: "Slack",
    slug: { current: "slack" },
    shortDescription: "Enhance team communication and collaboration with Slack integration.",
    description: "Enhance team communication and collaboration with Slack integration.",
    agentCount: 4,
  },
  {
    _id: "conn-94",
    title: "Smartsheet",
    slug: { current: "smartsheet" },
    shortDescription: "Improve project management and collaboration with Smartsheet.",
    description: "Improve project management and collaboration with Smartsheet.",
    agentCount: 4,
  },
  {
    _id: "conn-95",
    title: "Snowflake",
    slug: { current: "snowflake" },
    shortDescription: "Improve data analytics with Snowflake's all-in-one cloud platform.",
    description: "Improve data analytics with Snowflake's all-in-one cloud platform.",
    agentCount: 3,
  },
  {
    _id: "conn-96",
    title: "Stripe",
    slug: { current: "stripe" },
    shortDescription: "Automate payment processing and financial tasks with Stripe.",
    description: "Automate payment processing and financial tasks with Stripe.",
    agentCount: 2,
  },
  {
    _id: "conn-97",
    title: "SurveyMonkey",
    slug: { current: "surveymonkey" },
    shortDescription: "Automate survey data collection and analysis with SurveyMonkey.",
    description: "Automate survey data collection and analysis with SurveyMonkey.",
    agentCount: 1,
  },
  {
    _id: "conn-98",
    title: "Textura",
    slug: { current: "textura" },
    shortDescription: "Automate construction payment processes with Oracle Textura.",
    description: "Automate construction payment processes with Oracle Textura.",
    agentCount: 6,
  },
  {
    _id: "conn-99",
    title: "TradeTapp",
    slug: { current: "tradetapp" },
    shortDescription: "Optimize subcontractor risk assessment with TradeTapp integration.",
    description: "Optimize subcontractor risk assessment with TradeTapp integration.",
    agentCount: 6,
  },
  {
    _id: "conn-100",
    title: "Trimble Connect",
    slug: { current: "trimble-connect" },
    shortDescription: "Sync with Trimble Connect for field-to-office data integration.",
    description: "Sync with Trimble Connect for field-to-office data integration.",
    agentCount: 8,
  },
];

export const PLACEHOLDER_CATEGORIES = [
  { _id: "cat-1", title: "Document Review", slug: { current: "document-review" }, description: "Agents that review and analyze construction documents." },
  { _id: "cat-2", title: "Field Operations", slug: { current: "field-operations" }, description: "Agents that streamline field reporting and operations." },
  { _id: "cat-3", title: "Cost Management", slug: { current: "cost-management" }, description: "Agents for budget tracking and cost analysis." },
  { _id: "cat-4", title: "Safety & Compliance", slug: { current: "safety-compliance" }, description: "Agents that help ensure jobsite safety and regulatory compliance." },
  { _id: "cat-5", title: "Preconstruction", slug: { current: "preconstruction" }, description: "Agents that assist with estimating, bid leveling, and pre-con workflows." },
];

export const PLACEHOLDER_GUIDES = [
  {
    _id: "guide-1",
    title: "How to Automate Construction Submittal Review with AI",
    slug: { current: "ai-agents-submittal-review" },
    excerpt: "Submittal review is one of the most time-consuming workflows in construction. Learn how AI agents can automate spec comparison, catch compliance gaps, and help reviewers focus on decisions rather than data comparison.",
    author: "Datagrid Team",
    publishedAt: "2024-12-15T00:00:00Z",
    readTime: 8,
    category: { title: "Workflows", slug: { current: "workflows" } },
    relatedAgentSlugs: ["summary-spec-submittal", "deep-dive-spec-submittal", "submittal-builder"],
    relatedConnectorSlugs: ["procore", "plangrid", "autodesk-build"],
  },
  {
    _id: "guide-2",
    title: "5 Ways AI is Transforming RFI Management in Construction",
    slug: { current: "ai-rfi-management" },
    excerpt: "RFIs are essential for construction communication, but poor quality RFIs and slow responses create project delays. Here's how AI is helping teams submit better RFIs and resolve questions faster.",
    author: "Datagrid Team",
    publishedAt: "2024-12-08T00:00:00Z",
    readTime: 6,
    category: { title: "Best Practices", slug: { current: "best-practices" } },
    relatedAgentSlugs: ["rfi-validator", "rfi-checker"],
    relatedConnectorSlugs: ["procore", "autodesk-build"],
  },
  {
    _id: "guide-3",
    title: "Construction Document Search: Beyond Keyword Matching",
    slug: { current: "construction-document-search" },
    excerpt: "Traditional keyword search doesn't work well for construction documents. Learn how AI-powered search understands context, relationships, and intent to deliver real answers instead of document lists.",
    author: "Datagrid Team",
    publishedAt: "2024-11-28T00:00:00Z",
    readTime: 7,
    category: { title: "Technology", slug: { current: "technology" } },
    relatedAgentSlugs: ["deep-search", "fast-ai-search"],
    relatedConnectorSlugs: ["procore", "google-drive"],
  },
  {
    _id: "guide-4",
    title: "Reducing Change Order Disputes with AI-Powered Analysis",
    slug: { current: "reducing-change-order-disputes" },
    excerpt: "Change orders are a leading source of disputes in construction. Discover how AI agents can validate scope, flag cost implications, and provide evidence-backed analysis before disagreements escalate.",
    author: "Datagrid Team",
    publishedAt: "2024-11-15T00:00:00Z",
    readTime: 9,
    category: { title: "Best Practices", slug: { current: "best-practices" } },
    relatedAgentSlugs: ["change-order", "change-analyser", "scope-checker"],
    relatedConnectorSlugs: ["procore", "sage-300-cre"],
  },
  {
    _id: "guide-5",
    title: "AI Safety Inspections: From Site Photos to Actionable Reports",
    slug: { current: "ai-safety-inspections" },
    excerpt: "Site safety inspections generate mountains of photos and notes that rarely get analyzed systematically. Learn how AI agents turn visual data into prioritized, field-ready safety findings.",
    author: "Datagrid Team",
    publishedAt: "2024-11-01T00:00:00Z",
    readTime: 5,
    category: { title: "Workflows", slug: { current: "workflows" } },
    relatedAgentSlugs: ["site-safety", "audit-agent"],
    relatedConnectorSlugs: ["procore", "plangrid"],
  },
  {
    _id: "guide-6",
    title: "The GC's Guide to AI Adoption in 2025",
    slug: { current: "gc-guide-ai-adoption" },
    excerpt: "Practical advice for general contractors looking to implement AI tools without disrupting existing workflows. Covers team buy-in, pilot programs, and measuring ROI on AI investments.",
    author: "Datagrid Team",
    publishedAt: "2024-10-20T00:00:00Z",
    readTime: 10,
    category: { title: "Industry", slug: { current: "industry" } },
    relatedAgentSlugs: ["deep-search", "submittal-builder", "daily-report"],
    relatedConnectorSlugs: ["procore", "google-drive"],
  },
];
